# Generated by Django 3.0 on 2022-10-14 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewrating',
            options={'verbose_name_plural': 'Reviews'},
        ),
    ]
