# Generated by Django 3.1 on 2022-07-05 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart_item',
            options={'verbose_name_plural': 'Cart Items'},
        ),
    ]
