# Generated by Django 3.1 on 2022-06-26 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useracc',
            options={'verbose_name_plural': 'Accounts'},
        ),
    ]
