# Generated by Django 3.0 on 2022-10-15 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='adress_line_1',
            new_name='address_line_1',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='adress_line_2',
            new_name='address_line_2',
        ),
    ]
