# Generated by Django 3.0 on 2022-10-01 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderedproduct',
            name='color',
        ),
        migrations.RemoveField(
            model_name='orderedproduct',
            name='size',
        ),
    ]
