# Generated by Django 3.0 on 2022-10-01 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_variation'),
        ('order', '0002_auto_20221001_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderedproduct',
            name='variation',
        ),
        migrations.AddField(
            model_name='orderedproduct',
            name='variations',
            field=models.ManyToManyField(blank=True, to='store.Variation'),
        ),
    ]
